ERROR | 2025-02-17 14:40:23,489 | root |  Due to some error, the comment with id = None was not created.
INFO | 2025-02-17 14:42:21,113 | root |  string
ERROR | 2025-02-17 14:42:21,116 | root |  Due to some error, the comment with id = None was not created.
INFO | 2025-02-17 14:42:55,847 | root |  string
INFO | 2025-02-17 14:42:55,848 | root |  string, 3
ERROR | 2025-02-17 14:42:55,851 | root |  Due to some error, the comment with id = None was not created.
INFO | 2025-02-17 14:44:49,508 | root |  string
ERROR | 2025-02-17 14:44:49,625 | root |  Due to some error, the comment with id = None was not created.
INFO | 2025-02-17 14:45:34,600 | root |  string
INFO | 2025-02-17 14:45:34,601 | root |  <app.database.models.comment.Comment object at 0x00000258C9D72270>
ERROR | 2025-02-17 14:45:34,604 | root |  Due to some error, the comment with id = None was not created.
INFO | 2025-02-17 14:46:45,766 | root |  string
INFO | 2025-02-17 14:46:45,767 | root |  <Model Comment id=None, user_id=3, post_id=None, text_content=string>
ERROR | 2025-02-17 14:46:45,770 | root |  Due to some error, the comment with id = None was not created.
INFO | 2025-02-17 14:49:28,459 | root |  string
INFO | 2025-02-17 14:49:28,460 | root |  <Model Comment id=None, user_id=3, post_id=1, text_content=string>
INFO | 2025-02-17 14:49:28,487 | root |  Comment with id = 1 by user = name was successfully created
INFO | 2025-02-17 15:07:58,010 | root |  [CommentPublic(text_content='madada', id=1, user_id=3, post_id=1, created_at=datetime.datetime(2025, 2, 17, 11, 49, 28), is_repost=False)]
INFO | 2025-02-17 15:45:42,903 | root |  Fetched 1 comments for post_id = 1, offset = 0, limit = 5
